version: 2.1 # Use v2.1 to enable orb usage.

# The Windows orb gives you everything you
# need to start using the Windows executor.
orbs:
  win: circleci/windows@2.2.0
haxe:
  "4.1.5"
jobs:
  build: # name of your job
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout
      - run: haxelib install lime
      - run: haxelib install openfl
      - run: haxelib install flixel
      - run: haxelib install hscript
      - run: haxelib install newgrounds
      - run: haxelib install flixel-ui
      - run: haxelib install flixel-addons
      - run: haxelib install hxcpp
      - run: haxelib git polymod https://github.com/larsiusprime/polymod.git
      - run: haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
      - run: haxelib run lime build windows -final